#ifndef ASLEADERBOARDSEARCHER_GLOBAL_H
#define ASLEADERBOARDSEARCHER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ASLEADERBOARDSEARCHER_LIBRARY)
#  define ASLEADERBOARDSEARCHER_EXPORT Q_DECL_EXPORT
#else
#  define ASLEADERBOARDSEARCHER_EXPORT Q_DECL_IMPORT
#endif

#endif // ASLEADERBOARDSEARCHER_GLOBAL_H
