#ifndef ASLEADERBOARDCHARTS_GLOBAL_H
#define ASLEADERBOARDCHARTS_GLOBAL_H


#include <QtCore/qglobal.h>

#if defined(ASLEADERBOARDCHARTS_LIBRARY)
#  define ASLEADERBOARDCHARTS_EXPORT Q_DECL_EXPORT
#else
#  define ASLEADERBOARDCHARTS_EXPORT Q_DECL_IMPORT
#endif

#endif // ASLEADERBOARDCHARTS_GLOBAL_H
