#ifndef ASLEADERBOARDSELECTOR_GLOBAL_H
#define ASLEADERBOARDSELECTOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ASLEADERBOARDSELECTOR_LIBRARY)
#  define ASLEADERBOARDSELECTOR_EXPORT Q_DECL_EXPORT
#else
#  define ASLEADERBOARDSELECTOR_EXPORT Q_DECL_IMPORT
#endif

#endif // ASLEADERBOARDSELECTOR_GLOBAL_H
