#ifndef ASSCORESELECTOR_GLOBAL_H
#define ASSCORESELECTOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ASSCORESELECTOR_LIBRARY)
#  define ASSCORESELECTOR_EXPORT Q_DECL_EXPORT
#else
#  define ASSCORESELECTOR_EXPORT Q_DECL_IMPORT
#endif

#endif // ASLEADERBOARDSELECTOR_GLOBAL_H
