#ifndef ASLEADERBOARDANALYZER_GLOBAL_H
#define ASLEADERBOARDANALYZER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ASLEADERBOARDANALYZER_LIBRARY)
#  define ASLEADERBOARDANALYZER_EXPORT Q_DECL_EXPORT
#else
#  define ASLEADERBOARDANALYZER_EXPORT Q_DECL_IMPORT
#endif

#endif // ASLEADERBOARDANALYZER_GLOBAL_H
