#ifndef ASSCOREANALYZER_GLOBAL_H
#define ASSCOREANALYZER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ASSCOREANALYZER_LIBRARY)
#  define ASSCOREANALYZER_LIBRARY_EXPORT Q_DECL_EXPORT
#else
#  define ASSCOREANALYZER_LIBRARY_EXPORT Q_DECL_IMPORT
#endif

#endif // ASSEARCHLEADERBOARDWIDGET_GLOBAL_H
